;; a set of colours that is OK but a little too bold...
(set-background-color "white")
(set-foreground-color "black")
(set-cursor-color     "red")
(set-face-background vvb-face "light goldenrod yellow")

(custom-set-faces
 '(font-lock-builtin-face           ((t (:foreground "Orchid4"       :bold t :italic nil))))
 '(font-lock-comment-face           ((t (:foreground "DarkGreen"     :bold nil :italic t))))
 '(font-lock-constant-face          ((t (:foreground "red"           :bold t :italic nil))))
 '(font-lock-function-name-face     ((t (:foreground "brown4"        :bold t))))
 '(font-lock-keyword-face           ((t (:foreground "DarkSlateBlue" :bold t :italic nil))))
 '(font-lock-reference-face         ((t (:foreground "red"))))
 '(font-lock-string-face            ((t (:foreground "brown"         :bold t :italic t))))
 '(font-lock-type-face              ((t (:foreground "blue"          :bold t :italic nil))))
 '(font-lock-variable-name-face     ((t (:foreground "magenta4"      :bold t :italic nil))))
 '(jde-java-font-lock-code-face     ((t (                            :bold t))))
 '(jde-java-font-lock-link-face     ((t (:foreground "blue"          :bold nil :italic t :underline t))))
 '(jde-java-font-lock-modifier-face ((t (:foreground "Orchid4"       :bold nil :italic nil))))
 '(jde-java-font-lock-number-face   ((t (:foreground "red"           :bold t :italic nil))))
 )
