
;;; .ecb-user-layouts.el --- user defined ECB-layouts

;; Copyright (C) 2001 Jesper Nordenberg
;; Copyright (C) 2001 Free Software Foundation, Inc.
;; Copyright (C) 2001 Klaus Berndl <klaus.berndl@sdm.de>

;; Author: Klaus Berndl <klaus.berndl@sdm.de>
;; Maintainer: Klaus Berndl <klaus.berndl@sdm.de>
;; Keywords: java, class, browser

;; This program is free software; you can redistribute it and/or modify it
;; under the terms of the GNU General Public License as published by the Free
;; Software Foundation; either version 2, or (at your option) any later
;; version.

;; This program is distributed in the hope that it will be useful, but WITHOUT
;; ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
;; FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
;; more details.

;; You should have received a copy of the GNU General Public License along
;; with GNU Emacs; see the file COPYING. If not, write to the Free Software
;; Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

;;; Commentary:

;; This file contains all user-defined ECB-layouts created by the command
;; `ecb-create-new-layout'.

;; !!! DO NOT EDIT THIS FILE MANUALLY - IT IS GENERATED BY ECB !!!

(ecb-layout-define "amiller-left-analysis" left nil
                   (ecb-split-ver 0.4 t)
                   (ecb-set-methods-buffer)
                   (other-window 1)
                   (ecb-split-ver 0.5 t)
                   (ecb-set-directories-buffer)
                   (other-window 1)
                   (ecb-set-history-buffer)
                   (other-window 5)
                   )

(ecb-layout-define "amiller-left-analysis_orig" left nil
                   (ecb-split-ver 0.2 t)
                   (ecb-set-methods-buffer)
                   (other-window 1)
                   (ecb-split-ver 0.8 t)
                   (ecb-set-directories-buffer)
                   (other-window 1)
                   (ecb-set-history-buffer)
                   (other-window 5)
                   )

(ecb-layout-define "amiller-right-analysis" right nil
                   (ecb-split-ver 0.30 t)
                   (ecb-set-methods-buffer)
                   (other-window 1)
                   (ecb-split-ver 0.30 t)
                   (ecb-set-history-buffer)
                   (other-window 1)
                   (ecb-set-directories-buffer)
                   (other-window 5)
                   )

(ecb-layout-define "amiller-left-text-edit" left nil
                   (ecb-split-ver 0.7 t)
                   (ecb-set-directories-buffer)
                   (other-window 1)
                   (ecb-set-history-buffer)
                   (other-window 4)
                   )

(ecb-layout-define "SAVED_amiller-left-right-analysis" left-right nil
                   ;; first, split the frame...
                   (ecb-split-ver 0.70 t)
                   (other-window 3)
                   (ecb-split-ver 0.70 t)

                   ;; then set the ecb buffers...
                   (other-window 2) (ecb-set-directories-buffer) ; upper left
                   (other-window 1) (ecb-set-history-buffer)     ; lower left
                   (other-window 2) (ecb-set-methods-buffer)     ; upper right
                   (other-window 1) (ecb-set-analyse-buffer)     ; lower right

                   ;; finally, leave focus in the main buffer...
                   (other-window 3)
                   )

(ecb-layout-define "amiller-left-right-analysis" left-right nil
                   ;; first, split the frame...
                   (ecb-split-ver 0.85 t)
                   (other-window 3)
                   (ecb-split-ver 0.75 t)

                   ;; then set the ecb buffers...
                   (other-window 2) (ecb-set-directories-buffer) ; upper left
                   (other-window 1) (ecb-set-history-buffer)     ; lower left
                   (other-window 2) (ecb-set-methods-buffer)     ; upper right
                   (other-window 1) (ecb-set-analyse-buffer)     ; lower right

                   ;; finally, leave focus in the main buffer...
                   (other-window 3)
                   )

(ecb-layout-define "amiller-left-right" left-right nil
                   ;; first, split the frame...
                   (ecb-split-ver 0.85 t)

                   ;; then set the ecb buffers...
                   (ecb-set-directories-buffer) ; upper left
                   (other-window 1) (ecb-set-history-buffer)     ; lower left
                   (other-window 2) (ecb-set-methods-buffer)     ; upper right

                   ;; finally, leave focus in the main buffer...
                   (other-window 3)
                   )

(ecb-layout-define "amiller-left-simple" left nil
                   ;; first, split the frame...
                   (ecb-split-ver 0.70 t)

                   ;; then set the ecb buffers...
                   (other-window 3) (ecb-set-directories-buffer) ; upper left
                   (other-window 1) (ecb-set-history-buffer)     ; lower left

                   ;; finally, leave focus in the main buffer...
                   (other-window 1)
                   )

(ecb-layout-define "amiller-right" right nil
                   (ecb-split-ver 0.5 t)
                   (ecb-set-methods-buffer)
                   (other-window 1)
                   (ecb-split-ver 0.3 t)
                   (ecb-set-history-buffer)
                   (other-window 1)
                   (ecb-set-directories-buffer)
                   (other-window 5)
                   )

(ecb-layout-define "amiller-left-long-dir" left nil
                   (ecb-split-ver 0.5 t)
                   (ecb-set-methods-buffer)
                   (other-window 1)
                   (ecb-split-ver 0.3 t)
                   (ecb-set-history-buffer)
                   (other-window 1)
                   (ecb-set-directories-buffer)
                   (other-window 5)
                   )

(ecb-layout-define "amiller-right-long-dir" right nil
                   (ecb-split-ver 0.5 t)
                   (ecb-set-methods-buffer)
                   (other-window 1)
                   (ecb-split-ver 0.3 t)
                   (ecb-set-history-buffer)
                   (other-window 1)
                   (ecb-set-directories-buffer)
                   (other-window 5)
                   )
