mv .aliases aliases
mv .ecb-tip-of-day.el ecb-tip-of-day.el
mv .ecb-user-layouts.el ecb-user-layouts.el
mv .emacs emacs
mv .emacs-almost-working-for-emacs-23.1 emacs-almost-working-for-emacs-23.1
mv .emacs-for-22.3 emacs-for-22.3
mv .emacs.before_ecb_2.32 emacs.before_ecb_2.32
mv .emacs.before_ecb_2.32__1 emacs.before_ecb_2.32__1
mv .emacs.before_ecb_2.32__2 emacs.before_ecb_2.32__2
mv .emacs.before_ecb_2.40 emacs.before_ecb_2.40
mv .emacs.font-experiment.el emacs.font-experiment.el
mv .emacs.osx.frame-size.el emacs.osx.frame-size.el
mv .emacs.save_2009.12.11 emacs.save_2009.12.11
mv .emacs.theme.amiller-1.el emacs.theme.amiller-1.el
mv .emacs.theme.amiller-2.el emacs.theme.amiller-2.el
mv .emacs.theme.amiller.el emacs.theme.amiller.el
mv .emacs.theme.nightvision.el emacs.theme.nightvision.el
mv .emacs.win32.el emacs.win32.el
mv .inputrc inputrc
mv .profile profile
mv .profile.completions profile.completions
mv .projects projects
